import path from 'path'
import markdownMagic from 'markdown-magic'
import {markdownTable} from 'markdown-table'
import githubApi from './githubApi.js'

export const generateArtifactsTable = function(content, options, config) {
    let workflows = config.workflows
    let artifactsTableData = [
        ['Artifact', 'Workflow']
    ]
    workflows.forEach((workflow) => {
        let workflow_name = `<a href=${workflow.run_url}>${workflow.name}</a>`
        let artifacts = workflow["artifacts"]
        artifacts.forEach((artifact) => {
            let artifact_name = `<a href=${artifact.url}>${artifact.name}</a>`
            artifactsTableData.push([artifact_name, workflow_name])
        })
    })

    let artifactsTable = markdownTable(artifactsTableData)
    artifactsTable = artifactsTable.concat('\n\nAuto generated by <a href="https://github.com/dineshsonachalam/Autodoc-workflow-artifacts">Autodoc-workflow-artifacts</a>')
    return artifactsTable
}

export const app = async function(inputFilePath, repo, branch, githubApiToken) {
    const github = new githubApi(repo, branch, githubApiToken)
    const workflowNames = await github.getWorkflowNames()
    const workflowIds   = await github.getWorkflowIds(workflowNames)
    const workflowArtifacts = await github.getWorkflowArtifacts(workflowIds)
    const config = {
        workflows: workflowArtifacts,
        transforms: {
          artifactsTable: generateArtifactsTable,
        },
    };
    const markdownPath = path.join(inputFilePath)
    markdownMagic(markdownPath, config)
    const message = `Added artifacts for the ${workflowArtifacts.length} workflows`
    return message
}








