import path from 'path'
import markdownMagic from 'markdown-magic'
import Table from 'table-builder'
import githubApi from './githubApi.js'


export const generateArtifactsTable = function(content, options, config) {
    let workflows = config.workflows
    let artifactsTableData = []
    let tableHeaders = { "artifact" : "Artifact", "workflow": "Workflow" };
    workflows.forEach((workflow) => {
        let workflow_name = `<a href=${workflow.run_url}>${workflow.name}</a>`
        let artifacts = workflow["artifacts"]
        artifacts.forEach((artifact) => {
            let artifact_name = `<a href=${artifact.url}>${artifact.name}</a>`
            artifactsTableData.push({
                "artifact": artifact_name,
                "workflow": workflow_name
            })
        })
    })
    let artifactsTable = ((new Table({'class': 'artifactsTable'}))
                            .setHeaders(tableHeaders)
                            .setData(artifactsTableData)
                            .render()
    )
    artifactsTable = artifactsTable.concat('<br><p>Auto generated by <a href="https://github.com/dineshsonachalam/Autodoc-workflow-artifacts">Autodoc-workflow-artifacts</a></p>')
    return artifactsTable
}

export const app = async function(inputFilePath, repo, branch, githubApiToken) {
    const github = new githubApi(repo, branch, githubApiToken)
    const workflowNames = await github.getWorkflowNames()
    const workflowIds   = await github.getWorkflowIds(workflowNames)
    const workflowInfo = await github.getWorkflowArtifacts(workflowIds)
    const config = {
        workflows: workflowInfo.workflowArtifacts,
        transforms: {
          artifactsTable: generateArtifactsTable,
        },
    };
    const markdownPath = path.join(inputFilePath)
    markdownMagic(markdownPath, config)
    const message = `Added ${workflowInfo.totalArtifacts} artifacts`
    return message
}








