// import path from 'path'
// import markdownMagic from 'markdown-magic'
// import {markdownTable} from 'markdown-table'

import path from 'path';
import githubApi from './githubApi.js'


// function artifactsTable(content, _options = {}, config) {
//   let result = markdownTable([
//       ['Artifact', 'Commit'],
//       ['<a href="https://github.com/dineshsonachalam/Lucid-Dynamodb/suites/2942883115/artifacts/67433873">Pytest Report 1</a>', '0123456789abcdef'],
//       ['<a href="https://github.com/dineshsonachalam/Lucid-Dynamodb/suites/2942883115/artifacts/67433873">Pytest Report 2</a>', 'fedcba9876543210'],
//     ])
//   result = result.concat('\n\nAuto generated by <a href="">Dinesh Sonachalam</a>');
  
//   return result
// }

// const config = {
//   transforms: {
//     artifactsTable: artifactsTable,
//   },
// };
// const markdownPath = path.join('./README.md')
// markdownMagic(markdownPath, config)
let repo = process.env.repo;
let branchInfo = process.env.branch.split("/")
let branch  = branchInfo[branchInfo.length - 1]
let githubApiToken = process.env.githubApiToken
const github = new githubApi(repo, branch, githubApiToken)

// owner="1", repo="2", branch="3", githubApiToken="4"
// github.ref -> Branch name -> refs/heads/master
// github.repository -> owner/repoName -> dineshsonachalam/Autodoc-workflow-artifacts
