import path from 'path'
import markdownMagic from 'markdown-magic'
import Table from 'table-builder'
import githubApi from './githubApi.js'

/**
 * Module to generate artifacts html table.
 * @param {String} content 
 * @param {Object} options 
 * @param {Object} config 
 * @returns {String} artifactsTable
 */
export const generateArtifactsTable = function(content, options, config) {
    let workflows = config.workflows
    let artifactsTableData = []
    let tableHeaders = { "artifact" : "Artifact", "workflow": "Workflow" };
    workflows.forEach((workflow) => {
        let workflow_name = `<a href=${workflow.run_url}>${workflow.name}</a>`
        let artifacts = workflow["artifacts"]
        artifacts.forEach((artifact) => {
            let artifact_name = `<a href=${artifact.url}>${artifact.name}</a>`
            artifactsTableData.push({
                "artifact": artifact_name,
                "workflow": workflow_name
            })
        })
    })
    let artifactsTable = ((new Table({'class': 'artifactsTable'}))
                            .setHeaders(tableHeaders)
                            .setData(artifactsTableData)
                            .render()
    )
    artifactsTable = artifactsTable.concat('<br><p>Auto generated by <a href="https://github.com/dineshsonachalam/Autodoc-workflow-artifacts">Autodoc-workflow-artifacts</a></p>')
    return artifactsTable
}

/**
 * @param {String} outputFilePath 
 * @param {String} repo 
 * @param {String} branch 
 * @param {String} githubApiToken 
 * @returns {String} message
 */
export const app = async function(category, outputFilePath, repo="", branch="", githubApiToken="") {
    const markdownPath = path.join(outputFilePath)
    if(category == "code-block"){
        markdownMagic(markdownPath)
        return `Autodocumented code-block in ${outputFilePath}`
    }else if(category == "json-to-html-table"){
        return `Converted JSON to HTML table. Then autodocumented HTML table in ${outputFilePath}`
    }else if(category == "workflow-artifacts-table"){
        const github = new githubApi(repo, branch, githubApiToken)
        const workflowNames = await github.getWorkflowNames()
        const workflowIds   = await github.getWorkflowIds(workflowNames)
        const workflowInfo = await github.getWorkflowArtifacts(workflowIds)
        const config = {
            workflows: workflowInfo.workflowArtifacts,
            transforms: {
              artifactsTable: generateArtifactsTable,
            },
        };
        markdownMagic(markdownPath, config)
        const message = `Autodocumented ${workflowInfo.totalArtifacts} artifacts in artifactsTable - ${outputFilePath}`
        return message
    }
}








